spring.application.name=airline-management-system
server.port=8080
spring.thymeleaf.cache=false
spring.datasource.url=jdbc:mysql://localhost:3306/airline?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Real Mobile OTP Verification System Properties
otp.sms.enabled=true
otp.sms.api.key=YOUR_FAST2SMS_API_KEY

